// Uses MapGenCaves from the supplied Alpha client jar, without constructing a world.
// javac -cp <reference>/apclient.jar -d out tools/oracle/CaveOracle.java
// java -cp "out;<reference>/apclient.jar" CaveOracle <output-header>
import java.io.PrintWriter;
import java.util.Arrays;
import net.minecraft.src.MapGenCaves;

public final class CaveOracle extends MapGenCaves
{
	public static void main(String[] args) throws Exception
	{
		try (PrintWriter out = new PrintWriter(args[0], "UTF-8"))
		{
			out.println("// Generated by tools/oracle/CaveOracle.java against the supplied apclient.jar on JDK 8.");
			out.println("#pragma once\nnamespace headless\n{\nstruct CaveRun { int count, tile; };");
			for (int fixture = 0; fixture < 3; ++fixture)
			{
				byte[] blocks = new byte[32768];
				Arrays.fill(blocks, (byte)1);
				if (fixture == 1)
					for (int x = 0; x < 16; ++x)
						for (int z = 0; z < 16; ++z)
							blocks[(x * 16 + z) * 128 + 12] = 9;
				CaveOracle cave = new CaveOracle();
				cave.field_1305_b.setSeed(123456789L);
				cave.func_869_a(0, 0, blocks, 8.0, fixture == 2 ? 40.0 : 8.0, 8.0,
					3.0f, 0.0f, 0.0f, fixture == 2 ? 0 : -1, 24, 0.5);
				out.println("static const CaveRun cave" + fixture + "[] = {");
				int start = 0;
				while (start < blocks.length)
				{
					int end = start + 1;
					while (end < blocks.length && blocks[end] == blocks[start]) ++end;
					out.println("\t{" + (end - start) + ", " + (blocks[start] & 255) + "},");
					start = end;
				}
				out.println("};");
			}
			out.println("}");
		}
	}
}
