// Compile with the supplied Alpha MathHelper.java and run on JDK 8:
// javac -d out <reference>/net/minecraft/src/MathHelper.java tools/oracle/MthOracle.java
// java -cp out MthOracle src/util/MthSinTable.h src/tools/headless/oracle/MthOracleData.h
import java.io.PrintWriter;
import java.lang.reflect.Field;
import net.minecraft.src.MathHelper;

public final class MthOracle
{
	private static long hash(long value, float sample)
	{
		int bits = Float.floatToRawIntBits(sample);
		for (int i = 0; i < 4; ++i)
			value = (value ^ ((bits >>> (i * 8)) & 255)) * 0x100000001b3L;
		return value;
	}

	public static void main(String[] args) throws Exception
	{
		Field field = MathHelper.class.getDeclaredField("SIN_TABLE");
		field.setAccessible(true);
		float[] table = (float[])field.get(null);
		try (PrintWriter out = new PrintWriter(args[0], "UTF-8"))
		{
			out.println("// Generated by tools/oracle/MthOracle.java from the supplied Alpha MathHelper on JDK 8.");
			out.println("#pragma once\n\nstatic const float mthSinTable[65536] = {");
			for (int i = 0; i < table.length; ++i)
			{
				out.print("\t" + Float.toHexString(table[i]) + "f,");
				out.print(i % 4 == 3 ? "\n" : " ");
			}
			out.println("};");
		}
		try (PrintWriter out = new PrintWriter(args[1], "UTF-8"))
		{
			out.println("// Generated by tools/oracle/MthOracle.java using the supplied Alpha MathHelper on JDK 8.");
			out.println("#pragma once\n\nnamespace headless\n{");
			long sinHash = 0xcbf29ce484222325L;
			long cosHash = sinHash;
			for (int i = 0; i < 65536; ++i)
			{
				float angle = (i + 0.25f) / 10430.378f;
				if (((int)(angle * 10430.378f) & 65535) != i)
					throw new AssertionError("unvisited sine index " + i);
				sinHash = hash(sinHash, MathHelper.sin(angle));
				cosHash = hash(cosHash, MathHelper.cos(angle));
			}
			out.printf("static const unsigned long long mthSinHash = 0x%xULL;%n", sinHash);
			out.printf("static const unsigned long long mthCosHash = 0x%xULL;%n", cosHash);
			out.println("struct MthCase { unsigned int angle, sin, cos; };\nstatic const MthCase mthCases[] = {");
			float[] angles = {0.0f, -0.0f, 0.1f, -0.1f, 1.0f, -1.0f, 3.1415927f,
				-3.1415927f, 6.2831855f, -6.2831855f, 12345.5f, -12345.5f,
				Float.MIN_VALUE, -Float.MIN_VALUE, Float.MAX_VALUE, -Float.MAX_VALUE,
				Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, Float.NaN,
				2147483648.0f / 10430.378f, -2147483648.0f / 10430.378f};
			for (float angle : angles)
			{
				out.printf("\t{0x%xU, 0x%xU, 0x%xU},%n", Float.floatToRawIntBits(angle),
					Float.floatToRawIntBits(MathHelper.sin(angle)), Float.floatToRawIntBits(MathHelper.cos(angle)));
			}
			out.println("};\n}");
		}
	}
}
