import java.util.Random;

/**
 * Emits the expected java.util.Random output table consumed by the headless
 * rng suite.
 *
 * Regenerate with a JDK 8 runtime (the era the port targets) and overwrite
 * src/tools/headless/oracle/RandomOracleData.h:
 *
 *   javac -d out tools/oracle/RandomOracle.java
 *   java -cp out RandomOracle > src/tools/headless/oracle/RandomOracleData.h
 *
 * The script below is a single fixed sequence of operations replayed against
 * one Random per seed, so it pins down both the produced values and how many
 * bits each call consumes.
 */
public final class RandomOracle
{
	/** java.util.Random.next is protected; expose it so next(bits) can be pinned too. */
	private static final class ExposedRandom extends Random
	{
		private static final long serialVersionUID = 1L;

		ExposedRandom(long seed)
		{
			super(seed);
		}

		int nextBits(int bits)
		{
			return super.next(bits);
		}
	}

	private static final long[] SEEDS = {
		0L,
		1L,
		-1L,
		42L,
		25214903917L,
		123456789L,
		-987654321L,
		8682522807148012L,
		1024L,
		-9223372036854775808L,
		9223372036854775807L,
	};

	private static final int[] BOUNDS = { 1, 2, 3, 4, 7, 10, 16, 17, 31, 32, 100, 1000, 32768, 2147483647 };

	private static final StringBuilder steps = new StringBuilder();
	private static int stepCount;

	public static void main(String[] args)
	{
		System.out.println("// Generated by tools/oracle/RandomOracle.java. Do not edit by hand.");
		System.out.println("// Oracle values produced by java.util.Random on a JDK 8 runtime.");
		System.out.println("#pragma once");
		System.out.println();
		System.out.println("namespace headless");
		System.out.println("{");
		System.out.println();
		System.out.println("enum class RandomOp");
		System.out.println("{");
		System.out.println("\tNext,");
		System.out.println("\tNextInt,");
		System.out.println("\tNextIntBound,");
		System.out.println("\tNextLong,");
		System.out.println("\tNextFloatBits,");
		System.out.println("\tNextDoubleBits,");
		System.out.println("\tNextGaussianBits,");
		System.out.println("\tNextBoolean,");
		System.out.println("};");
		System.out.println();
		System.out.println("struct RandomOracleStep");
		System.out.println("{");
		System.out.println("\tRandomOp op;");
		System.out.println("\tint arg;");
		System.out.println("\tunsigned long long expected;");
		System.out.println("};");
		System.out.println();
		System.out.println("struct RandomOracleGroup");
		System.out.println("{");
		System.out.println("\tlong long seed;");
		System.out.println("\tconst RandomOracleStep *steps;");
		System.out.println("\tint stepCount;");
		System.out.println("};");
		System.out.println();

		StringBuilder groups = new StringBuilder();
		for (int index = 0; index < SEEDS.length; ++index)
		{
			steps.setLength(0);
			stepCount = 0;
			script(SEEDS[index]);

			System.out.println("static const RandomOracleStep randomOracleSteps" + index + "[] = {");
			System.out.print(steps);
			System.out.println("};");
			System.out.println();

			final long seed = SEEDS[index];
			final String seedLiteral = seed == Long.MIN_VALUE
				? "(-9223372036854775807LL - 1LL)"
				: seed + "LL";
			groups.append("\t{ ").append(seedLiteral).append(", randomOracleSteps").append(index)
				.append(", ").append(stepCount).append(" },\n");
		}

		System.out.println("static const RandomOracleGroup randomOracleGroups[] = {");
		System.out.print(groups);
		System.out.println("};");
		System.out.println();
		System.out.println("static const int randomOracleGroupCount ="
			+ " static_cast<int>(sizeof(randomOracleGroups) / sizeof(randomOracleGroups[0]));");
		System.out.println();
		System.out.println("}");
	}

	private static void script(long seed)
	{
		ExposedRandom random = new ExposedRandom(seed);

		for (int repeat = 0; repeat < 3; ++repeat)
		{
			for (int bits = 1; bits <= 32; ++bits)
				emit("Next", bits, unsignedInt(random.nextBits(bits)));

			for (int i = 0; i < 4; ++i)
				emit("NextInt", 0, unsignedInt(random.nextInt()));

			for (int bound : BOUNDS)
				emit("NextIntBound", bound, unsignedInt(random.nextInt(bound)));

			for (int i = 0; i < 4; ++i)
				emit("NextLong", 0, random.nextLong());

			for (int i = 0; i < 4; ++i)
				emit("NextFloatBits", 0, Integer.toUnsignedLong(Float.floatToRawIntBits(random.nextFloat())));

			for (int i = 0; i < 4; ++i)
				emit("NextDoubleBits", 0, Double.doubleToRawLongBits(random.nextDouble()));

			// Five calls exercise both the freshly computed value and the
			// cached second value of the polar method.
			for (int i = 0; i < 5; ++i)
				emit("NextGaussianBits", 0, Double.doubleToRawLongBits(random.nextGaussian()));

			for (int i = 0; i < 8; ++i)
				emit("NextBoolean", 0, random.nextBoolean() ? 1L : 0L);
		}
	}

	private static long unsignedInt(int value)
	{
		return Integer.toUnsignedLong(value);
	}

	private static void emit(String op, int arg, long expected)
	{
		steps.append("\t{ RandomOp::").append(op).append(", ").append(arg).append(", ")
			.append(Long.toUnsignedString(expected)).append("ULL },\n");
		++stepCount;
	}
}
