// javac -cp <reference>/apclient.jar -d out tools/oracle/TerrainOracle.java
// java -cp "out;<reference>/apclient.jar" TerrainOracle <output-header>
// The client jar supplies all generation code. The world uses an empty client
// cache to avoid disk I/O and population while testing undecorated chunk bytes.
import java.io.File;
import java.io.PrintWriter;
import net.minecraft.src.*;

public final class TerrainOracle
{
	private static final class OracleWorld extends World
	{
		OracleWorld(long seed) { super("oracle", new WorldProvider(), seed); }
		protected IChunkProvider func_4081_a(File file) { return new ChunkProviderClient(this); }
	}
	public static void main(String[] args) throws Exception
	{
		long[] seeds = {0L, 4242424242L, -123456789L};
		int[][] coords = {{0, 0}, {-3, 5}};
		try (PrintWriter out = new PrintWriter(args[0], "UTF-8"))
		{
			out.println("// Generated by tools/oracle/TerrainOracle.java using the supplied apclient.jar on JDK 8.");
			out.println("#pragma once\nnamespace headless\n{\nstruct TerrainRun { int count, tile; };");
			int fixture = 0;
			for (long seed : seeds)
				for (int[] coord : coords)
				{
					World world = new OracleWorld(seed);
					ChunkProviderGenerate generator = new ChunkProviderGenerate(world, seed);
					byte[] blocks = generator.provideChunk(coord[0], coord[1]).blocks;
					out.println("static const TerrainRun terrain" + fixture++ + "[] = {");
					int start = 0;
					while (start < blocks.length)
					{
						int end = start + 1;
						while (end < blocks.length && blocks[end] == blocks[start]) ++end;
						out.println("\t{" + (end - start) + ", " + (blocks[start] & 255) + "},");
						start = end;
					}
					out.println("};");
				}
			out.println("}");
		}
	}
}
